services:
  backend:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
      - db
    env_file:
      - .env
    command: celery -A app.core.celery.celery_app worker --loglevel=info

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # ✅ IMPORTANT

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

# ✅ DEFINE VOLUME HERE
volumes:
  postgres_data: